### ISSUE TITLE
parallelization to a cluster

### ISSUE THREAD

**Issue by sahilseth** [ChristofferFlensburg/superFreq#38]
I wanted to check a few things before starting a few parallel jobs.

Using a test run, I see that superfreq creates a bunch of coverage files for common normals. This step is done once - so that's perfect.

For variants, it seems sample variants are collected, and then are queried in the normal bams. Then `rda` files are saved in the common bams dir. Was wondering if multiple independent runs would clash while write in the same folder. (I think not, since you are using `round(runif(1,1,1e10)), '.Rdata` at `getVariantsByIndividual.R#L879`: https://github.com/ChristofferFlensburg/superFreq/blob/5fc70308a31143b152415b92c05f19fa55f0e19f/R/getVariantsByIndividual.R#L879)

Any thoughts about creating a gVCF for the normals (major processing upfront, but may be faster later?).

Are there any other considerations when submitting mutiple superfreq runs (each sample set would be run on a separate folder)?

**Comment by ChristofferFlensburg** [comment]
Hi!

Yep, you understood how it works, and I have that random barcode exactly to handle many parallel runs against same reference normals. It's been a major (MAJOR!) headache, because I was trying to set it up with locked files first, but I dropped that and it should be working without glitches now. I've done up to 377 parallel runs against the same reference normals and it's been working fine as far as I can tell.

I had to google what a gVCF is, and it seems like a VCF with an entry for every base in the genome? I don't think it's a good idea to pre-check the reference normals at every location. A typical exome analysis will look at 30k-100k locations, while the exome covers around 50M bases. RNA-Seq and genomes will have similar fractions. It'd take 1000x the time, which would be prohibitive. Even if you run 1000x samples, it'll mostly be the same variants over and over (common population variants and recurring noise), so no need to pre-check positions you will never care about.

**Comment by ChristofferFlensburg** [comment]
For multiple parallel runs, just make sure to use `splitRun=T` in the superFreq() call (for all jobs), and set the individual you want to analyse in each specific job through `participants='myIndividualForThisJob'`. Otherwise you can use the exact same call for all parallel runs in the same batch, and you can use a single giant meta data sheet with all the individuals in the cohort. Each individual be have it's own subdirectory in the `plotDirectory` and `Rdirectory`, which ties in nicely to the cohort afterburner.

Do you know about the cohort afterburner btw?? It finds genes that are hit in many patients in the cohort and it gives you average CNA rates across samples and so on. It's not really well documented and I haven't advertised it much, but I think it's working pretty well, although somewhat clunky in some ways. How many samples do you have? :)

**Comment by ChristofferFlensburg** [comment]
This an example of a .R script I was using when submitting a few mouse genomes to our HPC.

``` R
library(superFreq)

donor = as.character(commandArgs(TRUE)[1])
cpus = as.numeric(commandArgs(TRUE)[2])
fr = forceRedoNothing()

superFreq(
          metaDataFile = 'metaData.tsv',
          genome='mm10',
          normalDirectory='/stornext/General/data/academic/grp_leukemia_genomics/normals/mm10genome',
          Rdirectory='R',
          plotDirectory='plots',
          reference='/stornext/General/data/academic/grp_leukemia_genomics/data/reference/mm10/mm10.fa',
          mode='genome',
          cpus=cpus,
          participants=donor,
          forceRedo = fr
          )
```

So it takes the individual and number of cpus as arguments when calling with Rscript, all other options the same. `splitRun` is `TRUE` by default.

Also I realise I"m using individual, donor and participant interchangeably here, I hope it doens't cause confusion... :P

**Comment by sahilseth** [comment]
Thanks for the great suggestions.

 Am currently working with about 40 in the cohort, would be cool to try after burner. 

I have a related question. I put a matched normal, flagged with YES in NORMAL column of metadata. However I still see it in river plots and in the somatic variants file. Is this expected?

**Comment by ChristofferFlensburg** [comment]
Yep, the normals are still there, mostly for show in the river I guess. Gives a nice viz if it's a time course with remission samples or something like that. May be some corner cases where a (non-germline) clone is present to some extent in a normal maybe, not sure...

The normal samples (the YES samples) in somaticVariants.xls output is a bit different and shows rare germline variants instead of somatic variants. So these are variants with low population frequencies that got annotated. I think it's only saving protein altering variants, so missense and LoF variants, but not 100% on that.

40 makes for a nice cohort analysis! :)
After all the superFreq runs are done, run this script:

``` R
library(superFreq)

metaDataFiles = list.files('splitMetaData', pattern='*.tsv', full.names=T)  #assumes you run from the directory where this exists. should be next to the metadata.tsv
batchDir = normalizePath('cohort')                       #target directory that will be created, name as you want.
superFreq:::ensureDirectoryExists(batchDir)
Rdirectories = list.dirs('R', recursive=F)               #your Rdirectory from the superFreq() runs. Change if not 'R'

paths = data.frame('metaDataFile' = metaDataFiles, 'Rdirectory'= Rdirectories)

targetMetaDataFile = paste0(batchDir, '/metaData.tsv')
targetRdirectory = paste0(batchDir, '/R')

mergedPaths = mergeBatches(paths, targetMetaDataFile, targetRdirectory)

metaData = importSampleMetaData(targetMetaDataFile)

metaData$PROJECT = 'ALL'           #set these two as you want. Doesn’t influence analysis, but names some directories and at most sets some labels in plots.
metaData$GROUP = 'diagnosis'


cohortMetaDataFile = paste0(batchDir, '/cohortMetaData.tsv')
write.table(metaData, file=cohortMetaDataFile, row.names=F, col.names=T, sep='\t', quote=F)


#set the cosmicDirectory to the cosmic subdirectory of the automatically downloaded superFreqResources
#also set the genome to hg19 or hg38, matching the superFreq() runs.
outputDirectories = list('Rdirectory'=targetRdirectory)
cohortAnalyseBatch(cohortMetaDataFile, outputDirectories, cpus=8, genome='hg38', cosmicDirectory='superFreqResources/COSMIC')
```

The script takes maybe 1h or so to run on 40 patients, maybe less. Not sure how much memory it uses. shouldn't be much more than the individual superFreq runs, and could be much less. I really haven't looked at that. This part isn't really streamlined for smooth usage, so let me know if there are issues. I probably should wrap this code snippet into a function and add it to the package.

Results in myTargetDirectory/plots/projects/myProject/*.pdf, such as this example from the 377 colorectal RNA-Seq samples from TCGA. :)
<img width="1440" alt="meanCNV" src="https://user-images.githubusercontent.com/9857320/54972957-05cc7780-4fe2-11e9-98d0-ecfe09209f1d.png">

**Comment by sahilseth** [comment]
That's super helpful! thanks a lot!
